### ISSUE TITLE
Won't run: "Unexpected token 'U', "Using Mine"... is not valid JSON"

### ISSUE THREAD

**Issue by balazshevesi** [arjunkmrm/mcp-minecraft#1]
Hello!

First of all i just want to say that this project looks really cool.

I tried to get it running on my computer (M2 Macbook Air), but i couldn't figure out how. I followed your steps and i got this in the logs:

```
[Server Error] Exception in thread "main" 
[Server Error] java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:359)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:641)

Failed to start: Error: java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:359)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:641)

    at Socket.<anonymous> (file:///Users/balazshevesi/.npm/_npx/5a278f8106b17971/node_modules/mcp-minecraft/dist/ServerManager.js:133:32)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:343:12)
    at readableAddChunk (node:internal/streams/readable:316:9)
    at Readable.push (node:internal/streams/readable:253:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

It's a of missmatch in the java versions. So I updated my java version and then specified it as an environment variable in the config.

My config looks like this now:
``` json
{
  "mcpServers": {
    "mcp-minecraft": {
      "env": {
        "JAVA_HOME": "/opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home"
      },
      "command": "npx",
      "args": [
        "-y",
        "mcp-minecraft@latest",
        "--server-jar",
        "/Users/balazshevesi/bruh/mc_mcp/server.jar"
      ]
    }
  }
}
```

This seems to resolve the version missmatch, but it still won't work.

Now I an getting this inside mcp.log (this is not the full log, only the 5 rows, the rest just contain more SyntaxErrors):
```
2024-12-24T23:02:33.563Z [info] Attempting to connect to MCP server mcp-minecraft...
2024-12-24T23:02:33.619Z [info] Connected to MCP server mcp-minecraft!
2024-12-24T23:02:37.853Z [error] Error in MCP connection to server mcp-minecraft: SyntaxError: Unexpected token 'U', "Using Mine"... is not valid JSON
2024-12-24T23:02:37.855Z [error] Error in MCP connection to server mcp-minecraft: SyntaxError: Unexpected token 'S', "Starting M"... is not valid JSON
2024-12-24T23:02:37.856Z [error] Error in MCP connection to server mcp-minecraft: SyntaxError: Unexpected token 'S', "[Server] EU"... is not valid JSON
```

And the mcp-server-mcp-minecraft.log is (somehow) completely empty.

I don't understand what is going wrong. Interestingly the minecraft server actually starts, and i can connect to it.

I would very much appreciate it if you could help me debug.

**Comment by arjunkmrm** [comment]
hey @balazshevesi, the syntax errors which you see are relatively harmless and are a result of the minecraft server logging using the same stream as the stdio transport (I'm trying to find a fix for this). As for the MCP not launching, one common reason could be a known bug: the java process initiated from a previous session is still running in the background when you launch a new claude session. Would recommend going to 'Activity Monitor' and force quitting the 'java' process or restarting your PC.

<img width="424" alt="Screenshot 2024-12-26 at 11 33 37 AM" src="https://github.com/user-attachments/assets/85f89ae1-3597-454b-8b33-065dc73f5dbb" />

**Comment by balazshevesi** [comment]
Yes that was it, thanks for the help!
